### ISSUE TITLE
Strange Error

### ISSUE THREAD

**Issue by Motara7** [earlSt1/vtt-macro-folders#11] opened 2021-03-30 20:45 UTC
When I execute a macro while the macro window is open, I get the following error:

TypeError: Cannot read property 'classList' of undefined
    at MacroConfig._updateObject (macro-folders.js:768)
    at async MacroConfig._onSubmit (foundry.js:5251)
    at async MacroConfig._onExecute (foundry.js:18233)
_onSubmit @ foundry.js:5253
async function (async)
_onSubmit @ foundry.js:5251
_onExecute @ foundry.js:18233
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

Also, sometimes (I don't know what the trigger is for the sometimes) all the macros in the macro pane begin flashing making them unusable for about a minute before it calms down. Find the Culprit is telling me this module is the cause, but I don't know if it's 100% reliable.

I am on Foundry VTT 0.7.9 and Pathfinder 1e 0.77.19.

Thanks for your help.

**Comment by earlSt1** [comment] 2021-03-30 21:17
Hi, so I've found the cause of the first issue, i've pushed an update to the test branch if you'd like to verify it's fixed (testing manifest here: https://raw.githubusercontent.com/earlSt1/vtt-macro-folders/master/test/module.json)

As for the second point. I've noticed this a few times in testing too. I've been unable to replicate it since which is quite annoying, but i know what you mean, they all flicker a lot. I'll keep this issue open for the second point you raised :)

**Comment by Motara7** [comment] 2021-03-31 00:08
Sorry for my ignorance. I don't know what you want me to do. Do I copy
paste that somewhere?

**Comment by Motara7** [comment] 2021-03-31 00:15
I copy/pasted the code into the module.js and tested it. I got the same
error. So, I disabled Macro Folders and tested a macro execute. It did not
generate the error. Then I re-enabled Macro Folders and tested again and
got the error:

TypeError: Cannot read property 'classList' of undefined
    at MacroConfig._updateObject (macro-folders.js:768)
    at async MacroConfig._onSubmit (foundry.js:5251)
    at async MacroConfig._onExecute (foundry.js:18233)
_onSubmit @ foundry.js:5253
async function (async)
_onSubmit @ foundry.js:5251
_onExecute @ foundry.js:18233
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2

**Comment by earlSt1** [comment] 2021-03-31 01:31
Sorry, so uninstall your current version of Macro folders, then click Install module and at the bottom of the window there should be a text box for a manifest link. Put the link i sent above in that text box and hit install. It will look like the same version but its actually the test branch

**Comment by Motara7** [comment] 2021-03-31 21:53
That did the trick! Thank you very much for your help with this. Your
module is very helpful to me because I have a metric crap-ton of macros. I
really appreciate your efforts.

**Comment by earlSt1** [comment] 2021-04-03 15:27
Fixed in v1.1.1 (you can update directly from your testing version, no need to reinstall) :smile:

**Closed as completed by earlSt1** 2021-04-03 15:27 UTC
Labels: bug
