### ISSUE TITLE
hidden-macros Folder

### ISSUE THREAD

**Issue by tjlanza** [earlSt1/vtt-macro-folders#21] opened 2021-06-18 15:08 UTC
Foundry 0.8.7, MF 1.2.2, libWrapper 1.7.1.0

The hidden-macros folder is presumably supposed to itself be hidden. It isn't, and if deleted it recreates itself.

![image](https://user-images.githubusercontent.com/21128724/122581479-1636f580-d025-11eb-9b19-e8a83ec17bce.png)

**Comment by earlSt1** [comment] 2021-06-18 17:19
That is strange, but also working as intended (the recreating part). Have you got any other modules installed and enabled?

**Comment by tjlanza** [comment] 2021-06-19 19:22
> That is strange, but also working as intended (the recreating part). Have you got any other modules installed and enabled?

Plenty installed; only libWrapper enabled.

**Comment by earlSt1** [comment] 2021-06-19 20:23
And which system +version are you running?

**Comment by tjlanza** [comment] 2021-06-21 19:11
A pre-existing FVTT 0.8.7 w/ Shadowrun 5th Edition 0.7.17 world has the problem.

I created a fresh world, one with SR5 (0.7.17) and one with D&D5E (1.3.5). Neither shows that folder, though neither has any macros or folders beyond dummy entries I made to test.

I deleted and reinstalled the module. The populated SR5 world still shows that folder.

**Comment by earlSt1** [comment] 2021-06-21 19:14
Right ok, so sounds like its world specific.

Can you send me your macro folders Export string? You can find it in the module settings, under Import/Export Configuration. Click Copy to Clipboard and paste your results here.

**Comment by tjlanza** [comment] 2021-06-21 19:16
{"hidden":{"macroList":[],"titleText":"hidden-macros"},"default":{"macroList":["buLL6vVaEUgpSGPI","kKqAkAdZ25J8V8Gr","lTbLjdGlHWJj1Hvb","jAXZzVTBTuNCBu3p","abbsKcZOlFvj5beD","iBKFHEvh1wjQz3Q4","NYjbFvhM3gccEO9R","Lx1JogiXyEOMejB1","VJpuEq3LbSzyAmbN","nkpuEjqvJ3bfDW8p","VBSBFjnVJCIg0htg"],"titleText":"Default","colorText":"#000000","_id":"default","fontColorText":"#FFFFFF","type":"Macro","entity":"MacroFolder","sorting":"a","parent":null,"pathToFolder":[],"folderIcon":null,"expanded":false,"visible":true,"id":"default"},"mfolder_3uv36h3t73n":{"titleText":"Magic","colorText":"#000000","macroList":["LWyDYOkL273WLRAy","J8Szn5MeQuXs94qJ","BUOjYErmpyOw882K","wgY2VUJGfcOdQIfu","uximACw4jflTrGce"],"folderList":[],"_id":"mfolder_3uv36h3t73n","pathToFolder":["mfolder_8cy7e5e676"],"folderIcon":null,"playerDefault":"none","fontColorText":"#FFFFFF","type":"Macro","entity":"MacroFolder","sorting":"a","parent":"mfolder_8cy7e5e676","expanded":false,"visible":true},"mfolder_abu9jbr3d2":{"titleText":"Doors","colorText":"#000000","macroList":["EPDnYZL0kTpH4e3J","BARGuZeofjSIRqUC","oTgNIAIIL4bkpKT8","pOqSOkT2NjyrGwzT","Kl7A58eGbUQmqTEL"],"folderList":[],"_id":"mfolder_abu9jbr3d2","pathToFolder":[],"folderIcon":null,"playerDefault":null,"fontColorText":"#FFFFFF","type":"Macro","entity":"MacroFolder","sorting":"a","parent":null,"expanded":true},"mfolder_ylm6jwqhdpo":{"titleText":"Core","colorText":"#cc6600","macroList":["jPI37diga2VlY81J","BfFvzUmL5zmCEvEB","b01REDMZ4lGo6x9Y","hYlrldZAfbvh3ZQS","R4Ef0nQY1F5TeiMz","n7JPRVibQBymBK9L","2dXf8CmMcyV4k5NI","UFrWFIgWHIsiM5St","23KhTZ48oJtV4MDd","OmkeK8GMamIsaCsN","ZnZusXbmmiNdvF4S","R86gVHCyIvzAeCFY","gpxwLt84hMjfoR18"],"folderList":[],"_id":"mfolder_ylm6jwqhdpo","pathToFolder":[],"folderIcon":"icons/vtt.png","playerDefault":"none","fontColorText":"#FFFFFF","type":"Macro","entity":"MacroFolder","sorting":"a","parent":null,"expanded":false,"visible":true},"mfolder_r8yac6pu19":{"titleText":"Tint","colorText":"#000000","macroList":["RDrXyeTFi03sqZO0","8QA4lxybbAWaaycV","Kt7n1yxS4q6x7tVE","YgFnCIKISaYHPKJF","ZBeqEbgw3ETZKPGt","sK1o9YcRaNNLT96W","HKaosJSUcC9VqDVj"],"folderList":[],"_id":"mfolder_r8yac6pu19","pathToFolder":[],"folderIcon":"worlds/srm206x/icons/macro/brush_%23FFFFFF.svg","playerDefault":"none","fontColorText":"#FFFFFF","type":"Macro","entity":"MacroFolder","sorting":"a","parent":null,"expanded":false,"visible":true},"mfolder_6x9xpyopaic":{"titleText":"Vehicles","colorText":"#000000","macroList":["QB90Fb1Xy6Vp7p84","UNRUEpMCtAzAgEdq"],"folderList":[],"_id":"mfolder_6x9xpyopaic","pathToFolder":[],"folderIcon":null,"playerDefault":null},"mfolder_0fzpx7324zm":{"titleText":"Token Attacher","colorText":"#000000","macroList":["oVtXHWIHcmhYGCX4","zJqKjYKUMFJ3JS5O","8duf2874xPXKNn6v","GK0buBLruZhfbuZj","bZdAFGFU9usTgGBf","btjwYsbsocP1OQuC","tQSGSYH30BqqX2W6","tMa7j7kSErt3ilap","mRD0tP7hqoYfdSN0"],"folderList":[],"_id":"mfolder_0fzpx7324zm","pathToFolder":[],"folderIcon":null,"playerDefault":null,"fontColorText":"#FFFFFF","type":"Macro","entity":"MacroFolder","sorting":"a","parent":null,"expanded":false},"mfolder_8cy7e5e676":{"titleText":"Shadowrun","colorText":"#660066","fontColorText":"#FFFFFF","type":"Macro","_id":"mfolder_8cy7e5e676","entity":"MacroFolder","sorting":"a","parent":null,"pathToFolder":[],"macroList":["iTiL6DWmjBhpyX9i"],"folderIcon":"worlds/srm206x/icons/sr_pink_distortion.png","expanded":false,"playerDefault":null,"visible":true},"mfolder_u5megteup7":{"titleText":"Lights & Vision","colorText":"#000000","fontColorText":"#FFFFFF","type":"Macro","_id":"mfolder_u5megteup7","entity":"MacroFolder","sorting":"a","parent":"mfolder_8cy7e5e676","pathToFolder":["mfolder_8cy7e5e676"],"macroList":["3GId0NiNDlvpXFwh","z5loExWCItzCcaBY","rVLjfOaw7mQPlok3","H94Zqb4544glhK0Y","MrABO9YWAiIZ8kp0"],"folderIcon":null,"expanded":false,"visible":true,"playerDefault":"none"},"mfolder_d5n5wrlz8i":{"titleText":"Multilevel Tokens","colorText":"#000000","fontColorText":"#FFFFFF","type":"Macro","_id":"mfolder_d5n5wrlz8i","entity":"MacroFolder","sorting":"a","parent":null,"pathToFolder":[],"macroList":["pgTuAcepjBwJP4aY","aKkyWmTFgaYVP4sI","O2CCVdhSgMiiCqxV"],"folderIcon":null,"expanded":false,"visible":true,"playerDefault":"none"}}

**Comment by earlSt1** [comment] 2021-06-21 19:20
Thanks, i'll check these out in a bit.

Are you getting any errors in the F12 console when you open the macro directory?

**Comment by tjlanza** [comment] 2021-06-21 19:26
No warnings or errors, just:
`Foundry VTT | Rendering MacroFolderDirectory`

Knowing that it will blow away the folders and I'll have to re-file everything... Would exporting from one of the behaving worlds and importing over this world clear up the issue?

**Comment by earlSt1** [comment] 2021-06-21 19:35
That shouldnt be an issue. Just had another look in the code and its a styling issue, so should be easily fixable.

In your initial image, is the Default folder empty or does it have stuff in it?

I'll come up with a macro in a bit and send it over which should determine why the hidden folder isnt being hidden

**Comment by tjlanza** [comment] 2021-06-21 19:39
The Default folder has 11 macros in it.

**Comment by earlSt1** [comment] 2021-06-21 21:53
Hmm, which client are you using out of curiosity? Chrome/Firefox or the Foundry application?

**Comment by tjlanza** [comment] 2021-06-22 00:01
Chrome on Windows, connected to an Ubuntu 20.04 host.

**Comment by earlSt1** [comment] 2021-07-03 14:38
Sorry for the wait. Can you try using the Custom CSS module and adding this rule there?: 
```css
.macro-folder[data-folder-id="hidden"]{
  display:none !important;
}
```

**Comment by tjlanza** [comment] 2021-07-05 00:11
It did not. The solution I ended up going with was blowing away all the folders. I then exported the settings, removed the entry for "hidden", and reimported it. So far, the "hidden" entry (as show in the list above) has not recreated itself.

**Comment by earlSt1** [comment] 2021-09-18 15:11
Closing for now as I've been unable to replicate it

**Closed as completed by earlSt1** 2021-09-18 15:11 UTC
Labels: bug

**Comment by AntJLopez** [comment] 2021-10-12 14:03
> 
> 
> It did not. The solution I ended up going with was blowing away all the folders. I then exported the settings, removed the entry for "hidden", and reimported it. So far, the "hidden" entry (as show in the list above) has not recreated itself.

I experienced this same issue and resolved it by manually removing the hidden-macros entry from the export JSON before re-importing it, as suggested by @tjlanza.
