### ISSUE TITLE
1.06, F0.7.5, PF2 - some macros are escaping from the Default folder, cannot be filtered to it

### ISSUE THREAD

**Issue by apoapostolov** [earlSt1/vtt-macro-folders#3] opened 2020-11-02 15:53 UTC
I noticed that a lot of player created Macros from items in PF2 are not properly marked as unassigned and not put into the Default folder.

![image](https://user-images.githubusercontent.com/4083812/97888875-536ba300-1d34-11eb-88b1-912e32355e26.png)

My export:

{"hidden":{"macroList":["1YzxXL5HUrLh1DSr","1xBVdHaxCHCRdB7q","6ZOAfsVwae6hJKkh","9NitpkfLcNYJSuxk","L665Hsi9HfCP1STO","TL6pHZFzqmPcp10T","TM7iOAJCtOQj2fLE","UkpJBMwSfTLWtZNw","Yfm2mKbMTrAkgpS1","fFO0ZmElEN9gMBU2","goIHvtB3fUWBFHuT","huWzVS2dzgg8IzjX","lufzkxtANLsHckly","qUg4cBQbQgBK6bJz","rVE9nazprLSizrif","zbxkCyzfL20G8qmS"],"titleText":"hidden-macros"},"mfolder_cxfpg57jxto":{"titleText":"For GM","colorText":"#77007d","macroList":["1OXDiNyojmjbLDYA","4Ea0cLscEyFy9F8Y","7dAekeLz6WrxYB6t","ASlDhky7ruqyAJi0","HGfy5rxTjtxMMdhX","J2lRcmtlcJQXYHBa","Qr0yl7ct1tDEgZCl","RY1mlxxnmYCpgzoD","aZEk00YVorAh2zk4","azPvgGuFCksQD7aS","gzOv3eDTd91IbVKg","jidEWzH20CBkc0Rk","kZxQeSzNJf8Yqq2f","nHfQZZTGlcsZBbcE","nZJ7NDSkR6BvatLI"],"folderList":[],"_id":"mfolder_cxfpg57jxto","pathToFolder":[],"folderIcon":null},"mfolder_mpy25rysips":{"titleText":"For Players","colorText":"#7d0003","macroList":["3jQCQ9ZJytz0gTAN","6hM1wPBKdxb2dgzb","HPERcPchI5OieEVL","NrD5sI45OLln8WXg","i2ql99TeLLhw08u9","l5hUyK8OQJNLfxNd","sCOjVaBsB3r5vWS4"],"folderList":[],"_id":"mfolder_mpy25rysips","pathToFolder":[],"folderIcon":null},"default":{"macroList":[],"titleText":"Default","colorText":"#000000","_id":"default"},"mfolder_m8qmqgcm7nd":{"titleText":"Custom Conditions","colorText":"#970081","macroList":["DTWvynM3hM4Gjpn5","PJXJ84xCyDMvGVpy","VrISMXS1wAbe0EkH"],"folderList":[],"_id":"mfolder_m8qmqgcm7nd","pathToFolder":[],"folderIcon":null,"playerDefault":null}}

**Comment by earlSt1** [comment] 2020-11-02 20:29
Hi, sorry i'm not too familiar with macros, are these created from importing items from a compendium? or importing macros from a compendium?

**Comment by apoapostolov** [comment] 2020-11-07 16:36
Apologies for not seeing your response These are imported from items that my players pull from their inventory on the macro hotkeys.

**Comment by earlSt1** [comment] 2020-11-08 23:28
Hmm, are you getting any errors in the console? I'm trying to replicate it on my dev server by dragging a weapon as a player to the macro bar, then opening the macro directory as a GM.

**Comment by earlSt1** [comment] 2020-12-22 10:32
@apoapostolov Sorry for the wait, but I think I've found why that's happening. Basically those macros that are displayed are meant to be Hidden macros, but for some reason I didn't add them to the hidden folder after I added the default folder changes (before the default changes macros were added to the Hidden folder when created, so this may be a result of that)


Could you reinstall using this manifest and check if it's still an issue? You should be able to find the macros listed there in your Unassigned section in the edit folder dialog

https://raw.githubusercontent.com/earlSt1/vtt-macro-folders/master/test/module.json

**Comment by earlSt1** [comment] 2020-12-31 19:34
I've included what I believe is the fix for this isssue in version 1.0.8, can you check once you update that the issue is gone?

**Comment by earlSt1** [comment] 2021-03-22 22:54
Should be fixed in latest release (v1.1.0). We can reopen it if you encounter it again

**Closed as completed by earlSt1** 2021-03-22 22:54 UTC
Labels: bug
